// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package db

import (
	"context"
)

const createAdmin = `-- name: CreateAdmin :one
INSERT INTO admins (email, firebase_uid)
VALUES ($1, $2) RETURNING id, email, firebase_uid, created_at
`

type CreateAdminParams struct {
	Email       string `json:"email"`
	FirebaseUid string `json:"firebase_uid"`
}

func (q *Queries) CreateAdmin(ctx context.Context, arg CreateAdminParams) (Admin, error) {
	row := q.db.QueryRow(ctx, createAdmin, arg.Email, arg.FirebaseUid)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirebaseUid,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminByFirebaseUID = `-- name: GetAdminByFirebaseUID :one
SELECT id, email, firebase_uid, created_at FROM admins WHERE firebase_uid = $1 LIMIT 1
`

func (q *Queries) GetAdminByFirebaseUID(ctx context.Context, firebaseUid string) (Admin, error) {
	row := q.db.QueryRow(ctx, getAdminByFirebaseUID, firebaseUid)
	var i Admin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirebaseUid,
		&i.CreatedAt,
	)
	return i, err
}
