// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: advance_requests.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAdvanceRequest = `-- name: CreateAdvanceRequest :one
INSERT INTO advance_requests (user_id, amount_xaf, status)
VALUES ($1, $2, $3) RETURNING id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, created_at, updated_at
`

type CreateAdvanceRequestParams struct {
	UserID    uuid.UUID      `json:"user_id"`
	AmountXaf pgtype.Numeric `json:"amount_xaf"`
	Status    RequestStatus  `json:"status"`
}

func (q *Queries) CreateAdvanceRequest(ctx context.Context, arg CreateAdvanceRequestParams) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, createAdvanceRequest, arg.UserID, arg.AmountXaf, arg.Status)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveRequestByUserID = `-- name: GetActiveRequestByUserID :one
SELECT id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, created_at, updated_at FROM advance_requests
WHERE user_id = $1 AND status IN ('initiated', 'pending')
LIMIT 1
`

func (q *Queries) GetActiveRequestByUserID(ctx context.Context, userID uuid.UUID) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, getActiveRequestByUserID, userID)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdvanceRequestByCampayRef = `-- name: GetAdvanceRequestByCampayRef :one
SELECT id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, created_at, updated_at FROM advance_requests WHERE campay_payout_ref = $1
`

func (q *Queries) GetAdvanceRequestByCampayRef(ctx context.Context, campayPayoutRef pgtype.Text) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, getAdvanceRequestByCampayRef, campayPayoutRef)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdvanceRequestByID = `-- name: GetAdvanceRequestByID :one
SELECT id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, created_at, updated_at FROM advance_requests WHERE id = $1
`

func (q *Queries) GetAdvanceRequestByID(ctx context.Context, id uuid.UUID) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, getAdvanceRequestByID, id)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdvanceRequests = `-- name: ListAdvanceRequests :many
SELECT id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, created_at, updated_at FROM advance_requests
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdvanceRequestsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAdvanceRequests(ctx context.Context, arg ListAdvanceRequestsParams) ([]AdvanceRequest, error) {
	rows, err := q.db.Query(ctx, listAdvanceRequests, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvanceRequest
	for rows.Next() {
		var i AdvanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountXaf,
			&i.Status,
			&i.CampayPayoutRef,
			&i.FailureReason,
			&i.PayoutDurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdvanceRequestsByUserID = `-- name: ListAdvanceRequestsByUserID :many
SELECT id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, created_at, updated_at FROM advance_requests
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAdvanceRequestsByUserID(ctx context.Context, userID uuid.UUID) ([]AdvanceRequest, error) {
	rows, err := q.db.Query(ctx, listAdvanceRequestsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvanceRequest
	for rows.Next() {
		var i AdvanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountXaf,
			&i.Status,
			&i.CampayPayoutRef,
			&i.FailureReason,
			&i.PayoutDurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdvanceRequestsWithUser = `-- name: ListAdvanceRequestsWithUser :many
SELECT ar.id, ar.user_id, ar.amount_xaf, ar.status, ar.campay_payout_ref, ar.failure_reason, ar.payout_duration_seconds, ar.created_at, ar.updated_at, u.email AS user_email
FROM advance_requests ar
JOIN users u ON ar.user_id = u.id
ORDER BY ar.created_at DESC
LIMIT $1 OFFSET $2
`

type ListAdvanceRequestsWithUserParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAdvanceRequestsWithUserRow struct {
	ID                    uuid.UUID      `json:"id"`
	UserID                uuid.UUID      `json:"user_id"`
	AmountXaf             pgtype.Numeric `json:"amount_xaf"`
	Status                RequestStatus  `json:"status"`
	CampayPayoutRef       pgtype.Text    `json:"campay_payout_ref"`
	FailureReason         pgtype.Text    `json:"failure_reason"`
	PayoutDurationSeconds pgtype.Int4    `json:"payout_duration_seconds"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	UserEmail             string         `json:"user_email"`
}

func (q *Queries) ListAdvanceRequestsWithUser(ctx context.Context, arg ListAdvanceRequestsWithUserParams) ([]ListAdvanceRequestsWithUserRow, error) {
	rows, err := q.db.Query(ctx, listAdvanceRequestsWithUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdvanceRequestsWithUserRow
	for rows.Next() {
		var i ListAdvanceRequestsWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AmountXaf,
			&i.Status,
			&i.CampayPayoutRef,
			&i.FailureReason,
			&i.PayoutDurationSeconds,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdvanceRequestStatus = `-- name: UpdateAdvanceRequestStatus :one
UPDATE advance_requests SET
    status = $2,
    failure_reason = $3,
    payout_duration_seconds = $4,
    campay_payout_ref = $5,
    updated_at = NOW()
WHERE id = $1 RETURNING id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, created_at, updated_at
`

type UpdateAdvanceRequestStatusParams struct {
	ID                    uuid.UUID     `json:"id"`
	Status                RequestStatus `json:"status"`
	FailureReason         pgtype.Text   `json:"failure_reason"`
	PayoutDurationSeconds pgtype.Int4   `json:"payout_duration_seconds"`
	CampayPayoutRef       pgtype.Text   `json:"campay_payout_ref"`
}

func (q *Queries) UpdateAdvanceRequestStatus(ctx context.Context, arg UpdateAdvanceRequestStatusParams) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, updateAdvanceRequestStatus,
		arg.ID,
		arg.Status,
		arg.FailureReason,
		arg.PayoutDurationSeconds,
		arg.CampayPayoutRef,
	)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
