// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_otps.sql

package db

import (
	"context"
	"time"
)

const cleanupExpiredOTPs = `-- name: CleanupExpiredOTPs :exec
DELETE FROM email_otps WHERE expires_at < NOW()
`

func (q *Queries) CleanupExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredOTPs)
	return err
}

const createEmailOTP = `-- name: CreateEmailOTP :one
INSERT INTO email_otps (email, code, expires_at)
VALUES ($1, $2, $3) RETURNING id, email, code, expires_at, created_at
`

type CreateEmailOTPParams struct {
	Email     string    `json:"email"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateEmailOTP(ctx context.Context, arg CreateEmailOTPParams) (EmailOtp, error) {
	row := q.db.QueryRow(ctx, createEmailOTP, arg.Email, arg.Code, arg.ExpiresAt)
	var i EmailOtp
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEmailOTP = `-- name: DeleteEmailOTP :exec
DELETE FROM email_otps WHERE email = $1
`

func (q *Queries) DeleteEmailOTP(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteEmailOTP, email)
	return err
}

const getEmailOTPByEmail = `-- name: GetEmailOTPByEmail :one
SELECT id, email, code, expires_at, created_at FROM email_otps WHERE email = $1 AND expires_at > NOW() ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetEmailOTPByEmail(ctx context.Context, email string) (EmailOtp, error) {
	row := q.db.QueryRow(ctx, getEmailOTPByEmail, email)
	var i EmailOtp
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
