// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (user_id, admin_id, event_type, metadata)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, admin_id, event_type, metadata, created_at
`

type CreateEventParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	AdminID   pgtype.UUID `json:"admin_id"`
	EventType string      `json:"event_type"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.UserID,
		arg.AdminID,
		arg.EventType,
		arg.Metadata,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AdminID,
		&i.EventType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listEvents = `-- name: ListEvents :many
SELECT id, user_id, admin_id, event_type, metadata, created_at FROM events
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListEventsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AdminID,
			&i.EventType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsWithUser = `-- name: ListEventsWithUser :many
SELECT e.id, e.user_id, e.admin_id, e.event_type, e.metadata, e.created_at, u.email AS user_email
FROM events e
LEFT JOIN users u ON e.user_id = u.id
ORDER BY e.created_at DESC
LIMIT $1 OFFSET $2
`

type ListEventsWithUserParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListEventsWithUserRow struct {
	ID        uuid.UUID   `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	AdminID   pgtype.UUID `json:"admin_id"`
	EventType string      `json:"event_type"`
	Metadata  []byte      `json:"metadata"`
	CreatedAt time.Time   `json:"created_at"`
	UserEmail pgtype.Text `json:"user_email"`
}

func (q *Queries) ListEventsWithUser(ctx context.Context, arg ListEventsWithUserParams) ([]ListEventsWithUserRow, error) {
	rows, err := q.db.Query(ctx, listEventsWithUser, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsWithUserRow
	for rows.Next() {
		var i ListEventsWithUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.AdminID,
			&i.EventType,
			&i.Metadata,
			&i.CreatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
