// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations_active.sql

package db

import (
	"context"
)

const getActiveInvitationByEmail = `-- name: GetActiveInvitationByEmail :one
SELECT id, email, status, invited_by, sent_at, accepted_at, updated_at FROM invitations
WHERE email = $1 AND status IN ('pending', 'sent', 'accepted')
LIMIT 1
`

func (q *Queries) GetActiveInvitationByEmail(ctx context.Context, email string) (Invitation, error) {
	row := q.db.QueryRow(ctx, getActiveInvitationByEmail, email)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.InvitedBy,
		&i.SentAt,
		&i.AcceptedAt,
		&i.UpdatedAt,
	)
	return i, err
}
