// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations_list.sql

package db

import (
	"context"
)

const listInvitations = `-- name: ListInvitations :many
SELECT id, email, status, invited_by, sent_at, accepted_at, updated_at FROM invitations ORDER BY sent_at DESC
`

func (q *Queries) ListInvitations(ctx context.Context) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Status,
			&i.InvitedBy,
			&i.SentAt,
			&i.AcceptedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
