// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations_update.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const updateInvitationStatus = `-- name: UpdateInvitationStatus :one
UPDATE invitations SET status = $1, updated_at = NOW() WHERE id = $2 RETURNING id, email, status, invited_by, sent_at, accepted_at, updated_at
`

type UpdateInvitationStatusParams struct {
	Status InvitationStatus `json:"status"`
	ID     uuid.UUID        `json:"id"`
}

func (q *Queries) UpdateInvitationStatus(ctx context.Context, arg UpdateInvitationStatusParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, updateInvitationStatus, arg.Status, arg.ID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Status,
		&i.InvitedBy,
		&i.SentAt,
		&i.AcceptedAt,
		&i.UpdatedAt,
	)
	return i, err
}
