// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"database/sql"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email, email_verified, firebase_uid, full_name,
    phone_number, phone_verified, status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, email, email_verified, firebase_uid, full_name, phone_number, phone_verified, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

type CreateUserParams struct {
	Email         string      `json:"email"`
	EmailVerified bool        `json:"email_verified"`
	FirebaseUid   string      `json:"firebase_uid"`
	FullName      pgtype.Text `json:"full_name"`
	PhoneNumber   string      `json:"phone_number"`
	PhoneVerified bool        `json:"phone_verified"`
	Status        UserStatus  `json:"status"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.EmailVerified,
		arg.FirebaseUid,
		arg.FullName,
		arg.PhoneNumber,
		arg.PhoneVerified,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirebaseUid,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified, firebase_uid, full_name, phone_number, phone_verified, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirebaseUid,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByFirebaseUID = `-- name: GetUserByFirebaseUID :one
SELECT id, email, email_verified, firebase_uid, full_name, phone_number, phone_verified, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at FROM users WHERE firebase_uid = $1 LIMIT 1
`

func (q *Queries) GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByFirebaseUID, firebaseUid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirebaseUid,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, email_verified, firebase_uid, full_name, phone_number, phone_verified, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerified,
			&i.FirebaseUid,
			&i.FullName,
			&i.PhoneNumber,
			&i.PhoneVerified,
			&i.Status,
			&i.IsTermsAccepted,
			&i.TermsAcceptedAt,
			&i.TermsVersion,
			&i.UserIpAtConsent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTermsAcceptance = `-- name: UpdateTermsAcceptance :one
UPDATE users SET
    is_terms_accepted = $2,
    terms_accepted_at = $3,
    terms_version = $4,
    user_ip_at_consent = $5,
    updated_at = NOW()
WHERE id = $1 RETURNING id, email, email_verified, firebase_uid, full_name, phone_number, phone_verified, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

type UpdateTermsAcceptanceParams struct {
	ID              uuid.UUID    `json:"id"`
	IsTermsAccepted bool         `json:"is_terms_accepted"`
	TermsAcceptedAt sql.NullTime `json:"terms_accepted_at"`
	TermsVersion    pgtype.Text  `json:"terms_version"`
	UserIpAtConsent *netip.Addr  `json:"user_ip_at_consent"`
}

func (q *Queries) UpdateTermsAcceptance(ctx context.Context, arg UpdateTermsAcceptanceParams) (User, error) {
	row := q.db.QueryRow(ctx, updateTermsAcceptance,
		arg.ID,
		arg.IsTermsAccepted,
		arg.TermsAcceptedAt,
		arg.TermsVersion,
		arg.UserIpAtConsent,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirebaseUid,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users SET status = $2, updated_at = NOW()
WHERE id = $1 RETURNING id, email, email_verified, firebase_uid, full_name, phone_number, phone_verified, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

type UpdateUserStatusParams struct {
	ID     uuid.UUID  `json:"id"`
	Status UserStatus `json:"status"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerified,
		&i.FirebaseUid,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
